/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package IniCea;

import Administrador.Adminn;
import G14.IniG14;
import G18.IniG18;
import G19.IniG19;
import G7.IniG7;
import Objetos.Conectar;
import Objetos.fondo;
import ceaa.ingres;
import java.awt.Dimension;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JLayeredPane;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Familia
 */
public class Personal extends javax.swing.JFrame {
   

    /**
     * Creates new form IniCea
     */
    public Personal() {
        initComponents();
        
         this.setResizable(false);
       fondo imagen =new fondo();
       String imagenes=imagen.fond();
        
        ((JPanel)getContentPane()).setOpaque(false);
            ImageIcon uno=new ImageIcon(this.getClass().getResource(imagenes));
          JLabel fondo= new JLabel(); 
          fondo.setIcon(uno);
          getLayeredPane().add(fondo, JLayeredPane.FRAME_CONTENT_LAYER);
          fondo.setBounds(0,0,uno.getIconWidth(),uno.getIconHeight());

         this.setSize(900,700);
         setLocationRelativeTo(null);  
         Date now = new Date(System.currentTimeMillis());
        SimpleDateFormat date = new SimpleDateFormat("dd-MM-yyyy");
        SimpleDateFormat hour = new SimpleDateFormat("HH:mm:ss");
        this.jLabel7.setText(date.format(now));
       this.jLabel8.setText(hour.format(now));
         
         //mostrarD("");
          try{
            Statement st = cn.createStatement();
            ResultSet rs = st.executeQuery("SELECT * FROM variable WHERE id='1'");
            
            String usu="";
            
            while(rs.next()){
             usu=rs.getString(2);
            }
            JLnombreUSU.setText(usu);
          
            
            
            
        }catch(Exception e){
        
        System.out.println("auditoria"+e);
        }
          
         datos();
         
         BtnBuscarArma.setVisible(false);
         BtnBuscarFame.setVisible(false);
         BtnBuscarProm.setVisible(false);
         BTNbuscarSit.setVisible(false);

    }
    
    
    void datos(){
    
     //UNIDAD
    //CMBBUSCAR.addItem("");
    CMBBUSCAR.addItem("C.E.A.");
    CMBBUSCAR.addItem("G7");
    CMBBUSCAR.addItem("G14");
    CMBBUSCAR.addItem("G18");
    CMBBUSCAR.addItem("G19");
    
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Centr = new javax.swing.JLabel();
        CEA = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        JLnombreUSU = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        TBperson = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        TXTced = new javax.swing.JTextField();
        BtnBuscarPER = new javax.swing.JButton();
        jPanel19 = new javax.swing.JPanel();
        jButton52 = new javax.swing.JButton();
        jButton53 = new javax.swing.JButton();
        jButton54 = new javax.swing.JButton();
        jButton56 = new javax.swing.JButton();
        jButton57 = new javax.swing.JButton();
        jButton58 = new javax.swing.JButton();
        BotonProm = new javax.swing.JButton();
        BotonArma = new javax.swing.JButton();
        BotonFami = new javax.swing.JButton();
        jButton59 = new javax.swing.JButton();
        BotonArma1 = new javax.swing.JButton();
        CMBBUSCAR = new javax.swing.JComboBox();
        BtnBuscarProm = new javax.swing.JButton();
        BtnBuscarFame = new javax.swing.JButton();
        BtnBuscarArma = new javax.swing.JButton();
        BTNbuscarSit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Personal");
        setUndecorated(true);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setOpaque(false);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Sin título-1.png"))); // NOI18N

        Centr.setFont(new java.awt.Font("Traditional Arabic", 1, 18)); // NOI18N
        Centr.setText("Centro de Entrenamiento Aéreo");

        CEA.setFont(new java.awt.Font("Traditional Arabic", 1, 24)); // NOI18N
        CEA.setText("C.E.A.");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addComponent(CEA))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Centr)))
                .addContainerGap(68, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(CEA)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Centr))
                    .addComponent(jLabel1))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jPanel6.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel6.setOpaque(false);

        jLabel11.setFont(new java.awt.Font("Traditional Arabic", 1, 14)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("C.E.A / Personal");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jButton1.setFont(new java.awt.Font("Traditional Arabic", 1, 14)); // NOI18N
        jButton1.setText("Opciones");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel3.setOpaque(false);

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Exit.png"))); // NOI18N
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Traditional Arabic", 1, 18)); // NOI18N
        jLabel12.setText("Usuario:");

        jLabel7.setFont(new java.awt.Font("Traditional Arabic", 1, 14)); // NOI18N
        jLabel7.setText("jLabel7");

        jLabel8.setFont(new java.awt.Font("Traditional Arabic", 1, 14)); // NOI18N
        jLabel8.setText("jLabel8");

        jLabel10.setFont(new java.awt.Font("Traditional Arabic", 1, 14)); // NOI18N
        jLabel10.setText("Hora:");

        jLabel13.setFont(new java.awt.Font("Traditional Arabic", 1, 14)); // NOI18N
        jLabel13.setText("Fecha:");

        JLnombreUSU.setFont(new java.awt.Font("Traditional Arabic", 1, 14)); // NOI18N
        JLnombreUSU.setText("Usuario");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JLnombreUSU, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addGap(11, 11, 11)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel8)
                                .addComponent(jLabel10)
                                .addComponent(jLabel13)))
                        .addGap(35, 35, 35)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(JLnombreUSU, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(45, 45, 45))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(14, 14, 14))))
        );

        TBperson.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7", "Title 8", "Title 9", "Title 10", "Title 11", "Title 12", "Title 13", "Title 14", "Title 15", "Title 16", "Title 17", "Title 18", "Title 19", "Title 20", "Title 21", "Title 22", "Title 23"
            }
        ));
        TBperson.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_LAST_COLUMN);
        jScrollPane3.setViewportView(TBperson);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 2498, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 393, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(jPanel2);

        jLabel9.setFont(new java.awt.Font("Traditional Arabic", 1, 14)); // NOI18N
        jLabel9.setText("Buscar por Cedula");

        BtnBuscarPER.setFont(new java.awt.Font("Traditional Arabic", 1, 14)); // NOI18N
        BtnBuscarPER.setText("Buscar");
        BtnBuscarPER.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBuscarPERActionPerformed(evt);
            }
        });

        jPanel19.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel19.setOpaque(false);

        jButton52.setFont(new java.awt.Font("Traditional Arabic", 1, 14)); // NOI18N
        jButton52.setText("Personal");
        jButton52.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton52ActionPerformed(evt);
            }
        });

        jButton53.setFont(new java.awt.Font("Traditional Arabic", 1, 14)); // NOI18N
        jButton53.setText("Guardias");
        jButton53.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton53ActionPerformed(evt);
            }
        });

        jButton54.setFont(new java.awt.Font("Traditional Arabic", 1, 14)); // NOI18N
        jButton54.setText("Actualizacion de Datos");
        jButton54.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton54ActionPerformed(evt);
            }
        });

        jButton56.setFont(new java.awt.Font("Traditional Arabic", 1, 14)); // NOI18N
        jButton56.setText("Inicio");
        jButton56.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton56ActionPerformed(evt);
            }
        });

        jButton57.setFont(new java.awt.Font("Traditional Arabic", 1, 14)); // NOI18N
        jButton57.setText("Formatos");
        jButton57.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton57ActionPerformed(evt);
            }
        });

        jButton58.setFont(new java.awt.Font("Traditional Arabic", 1, 14)); // NOI18N
        jButton58.setText("Parte");
        jButton58.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton58ActionPerformed(evt);
            }
        });

        BotonProm.setFont(new java.awt.Font("Traditional Arabic", 1, 14)); // NOI18N
        BotonProm.setText("Promocion");
        BotonProm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonPromActionPerformed(evt);
            }
        });

        BotonArma.setFont(new java.awt.Font("Traditional Arabic", 1, 14)); // NOI18N
        BotonArma.setText("Armamento");
        BotonArma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonArmaActionPerformed(evt);
            }
        });

        BotonFami.setFont(new java.awt.Font("Traditional Arabic", 1, 14)); // NOI18N
        BotonFami.setText("Familiares");
        BotonFami.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonFamiActionPerformed(evt);
            }
        });

        jButton59.setFont(new java.awt.Font("Traditional Arabic", 1, 14)); // NOI18N
        jButton59.setText("Unidades");
        jButton59.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton59ActionPerformed(evt);
            }
        });

        BotonArma1.setFont(new java.awt.Font("Traditional Arabic", 1, 14)); // NOI18N
        BotonArma1.setText("Situacion");
        BotonArma1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonArma1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel19Layout = new javax.swing.GroupLayout(jPanel19);
        jPanel19.setLayout(jPanel19Layout);
        jPanel19Layout.setHorizontalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButton53, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButton54, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButton52, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButton56, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButton57, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButton58, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButton59, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel19Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BotonFami, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotonProm, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotonArma, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotonArma1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        jPanel19Layout.setVerticalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel19Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton56)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton59)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton52)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BotonFami)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BotonProm)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BotonArma, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BotonArma1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton53)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton58)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton54)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton57)
                .addGap(33, 33, 33))
        );

        CMBBUSCAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CMBBUSCARActionPerformed(evt);
            }
        });

        BtnBuscarProm.setFont(new java.awt.Font("Traditional Arabic", 1, 14)); // NOI18N
        BtnBuscarProm.setText("Buscar");
        BtnBuscarProm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBuscarPromActionPerformed(evt);
            }
        });

        BtnBuscarFame.setFont(new java.awt.Font("Traditional Arabic", 1, 14)); // NOI18N
        BtnBuscarFame.setText("Buscar");
        BtnBuscarFame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBuscarFameActionPerformed(evt);
            }
        });

        BtnBuscarArma.setFont(new java.awt.Font("Traditional Arabic", 1, 14)); // NOI18N
        BtnBuscarArma.setText("Buscar");
        BtnBuscarArma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBuscarArmaActionPerformed(evt);
            }
        });

        BTNbuscarSit.setFont(new java.awt.Font("Traditional Arabic", 1, 14)); // NOI18N
        BTNbuscarSit.setText("Buscar");
        BTNbuscarSit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNbuscarSitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 651, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TXTced, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(BtnBuscarPER)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BtnBuscarFame)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BtnBuscarProm)
                                .addGap(2, 2, 2)
                                .addComponent(BtnBuscarArma)
                                .addGap(4, 4, 4)
                                .addComponent(BTNbuscarSit)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CMBBUSCAR, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1)))
                        .addGap(79, 79, 79))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 146, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel9)
                                .addComponent(TXTced, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(BtnBuscarPER, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(BtnBuscarFame, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(BtnBuscarProm, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(BtnBuscarArma, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(BTNbuscarSit, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(CMBBUSCAR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(17, 17, 17)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

  
   /* void mostrarD(String valor){
    DefaultTableModel model = new DefaultTableModel();
    model.addColumn("cedula");
    model.addColumn("nombre");
    model.addColumn("apellido");
    
    model.addColumn("Serial del Carnet");
    model.addColumn("sexo");
    model.addColumn("alergias");
    model.addColumn("grupo sanguineos");
    model.addColumn("Unidad");
    model.addColumn("BETOJOSE");
    
    //grado
        model.addColumn("grado");
    model.addColumn("carrera");
    model.addColumn("fecha de nacimiento");
    model.addColumn("estado civil");
    model.addColumn("promocion");


    model.addColumn("serial de armamento");
    model.addColumn("fecha de ingreso al sistema");
    model.addColumn("telefono celular");
    model.addColumn("telefono otro ");
    model.addColumn("telefono de casa");
    model.addColumn("telefono de trabajo");
    model.addColumn("correo");
    model.addColumn("direccion ");
    model.addColumn("centro de votacion");
    model.addColumn("ubicacion del centro de votacion");
    
    TBperson.setModel(model);
    
    String sql="";
    if(valor.equals("")){
    
    sql="SELECT * FROM personal"; 
    
    }
    else{
    sql="SELECT * FROM personal WHERE ced_per='"+valor+"'";
    
    }
        
    String []dato = new String[23];
        try {
            Statement st = cn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while(rs.next()){
            dato[0]=rs.getString(1);
            dato[1]=rs.getString(2);
            dato[2]=rs.getString(3); 
            dato[3]=rs.getString(4);
            dato[4]=rs.getString(5); 
            dato[5]=rs.getString(6);
            dato[6]=rs.getString(7);
            dato[7]=rs.getString(8);
            dato[8]=rs.getString(9);
            dato[9]=rs.getString(10);
            dato[10]=rs.getString(11);
            dato[11]=rs.getString(12);
            dato[12]=rs.getString(13);
            dato[13]=rs.getString(14);
            dato[14]=rs.getString(15);
            dato[15]=rs.getString(16);
            dato[16]=rs.getString(17);
            dato[17]=rs.getString(18);
            dato[18]=rs.getString(19);
            dato[19]=rs.getString(20);
            dato[20]=rs.getString(21);
            dato[21]=rs.getString(22);
            dato[22]=rs.getString(23);
            
               
            model.addRow(dato);
            }
            TBperson.setModel(model);
        } catch (SQLException ex) {
            System.out.println(ex+"  es aca");
           
        }



}*/
    
    
    void mostrarUni(String valor){
    DefaultTableModel model = new DefaultTableModel();
    model.addColumn("cedula");
    model.addColumn("nombre");
    model.addColumn("apellido");model.addColumn("apellido");model.addColumn("apellido");
    
    model.addColumn("Serial del Carnet");
    model.addColumn("sexo");
    model.addColumn("alergias");
    model.addColumn("grupo sanguineos");
    model.addColumn("Unidad");
    model.addColumn("fecha de nacimiento");
    model.addColumn("estado civil");
    model.addColumn("promocion");

    model.addColumn("grado");
    model.addColumn("carrera");
    model.addColumn("serial de armamento");
    model.addColumn("fecha de ingreso al sistema");
    model.addColumn("telefono celular");
    model.addColumn("telefono otro ");
    model.addColumn("telefono de casa");
    model.addColumn("telefono de trabajo");
    model.addColumn("correo");
    model.addColumn("direccion ");
    model.addColumn("centro de votacion");
    model.addColumn("ubicacion del centro de votacion");
    
    TBperson.setModel(model);
    String sql="";
    if(valor.equals("")){
    
    sql="SELECT * FROM personal"; 
    
    }
    else{
    sql="SELECT * FROM personal WHERE unidad='"+valor+"'";
    
    }
        
    String []dato = new String[23];
        try {
            Statement st = cn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while(rs.next()){
            dato[0]=rs.getString(1);
            dato[1]=rs.getString(2);
            dato[2]=rs.getString(3); 
            dato[3]=rs.getString(4);
            dato[4]=rs.getString(5); 
            dato[5]=rs.getString(6);
            dato[6]=rs.getString(7);
            dato[7]=rs.getString(8);
            dato[8]=rs.getString(9);
            dato[9]=rs.getString(10);
            dato[10]=rs.getString(11);
            dato[11]=rs.getString(12);
            dato[12]=rs.getString(13);
            dato[13]=rs.getString(14);
            dato[14]=rs.getString(15);
            dato[15]=rs.getString(16);
            dato[16]=rs.getString(17);
            dato[17]=rs.getString(18);
            dato[18]=rs.getString(19);
            dato[19]=rs.getString(20);
            dato[20]=rs.getString(21);
            dato[21]=rs.getString(22);
            dato[22]=rs.getString(23);
            
               
            model.addRow(dato);
            }
            TBperson.setModel(model);
        } catch (SQLException ex) {
            System.out.println(ex+"  es aca");
           
        }



}
        
         
      void mostrarSitua(String valor){
    DefaultTableModel model = new DefaultTableModel();
    model.addColumn("Cedula");
    model.addColumn("Situacion");
    model.addColumn("Descripcion");
    
    model.addColumn("Ubicacion");
    model.addColumn("Fecha de Inicio");
    model.addColumn("Fecha de Finalizacion");
    model.addColumn("Status");
    TBperson.setModel(model);
    String sql="";
    if(valor.equals("")){
    
    sql="SELECT * FROM situacion"; 
    
    }
    else{
    sql="SELECT * FROM situacion WHERE ced_per='"+valor+"'";
    
    }
        
    String []dato = new String[7];
        try {
            Statement st = cn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while(rs.next()){
            dato[0]=rs.getString(2);
            dato[1]=rs.getString(3);
            dato[2]=rs.getString(4); 
            dato[3]=rs.getString(5);
            dato[4]=rs.getString(6); 
            dato[5]=rs.getString(7);
            dato[6]=rs.getString(8);  
               
            model.addRow(dato);
            }
            TBperson.setModel(model);
        } catch (SQLException ex) {
            System.out.println(ex+"  es aca");
           
        }



}
      

      void mostrarPromo(String valor){
    DefaultTableModel model = new DefaultTableModel();
    model.addColumn("id_prom");
    model.addColumn("nombre promo");
    model.addColumn("año promo");
    
    model.addColumn("escuela de promocion");
    model.addColumn("especialidad");
    model.addColumn("mencion");
    TBperson.setModel(model);
    String sql="";
    if(valor.equals("")){
    
    sql="SELECT * FROM promocion"; 
    
    }
    else{
    sql="SELECT * FROM promocion WHERE id_prom='"+valor+"'";
    
    }
        
    String []dato = new String[6];
        try {
            Statement st = cn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while(rs.next()){
            dato[0]=rs.getString(1);
            dato[1]=rs.getString(2);
            dato[2]=rs.getString(3); 
            dato[3]=rs.getString(4);
            dato[4]=rs.getString(5); 
            dato[5]=rs.getString(6);  
               
            model.addRow(dato);
            }
            TBperson.setModel(model);
        } catch (SQLException ex) {
            System.out.println(ex+"  es aca");
           
        }



}
      
      void mostrararma (String valor){
    DefaultTableModel model = new DefaultTableModel();
    model.addColumn("ser_armp");
    model.addColumn("tipo arma");
    model.addColumn("ubicacion");
    
    model.addColumn("observacion");
    model.addColumn("Status");
    TBperson.setModel(model);
    String sql="";
    if(valor.equals("")){
    
    sql="SELECT * FROM armamentop"; 
    
    }
    else{
    sql="SELECT * FROM armamentop WHERE ser_armp='"+valor+"'";
    
    }
        
    String []dato = new String[5];
        try {
            Statement st = cn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while(rs.next()){
            dato[0]=rs.getString(1);
            dato[1]=rs.getString(2);
            dato[2]=rs.getString(3); 
            dato[3]=rs.getString(4);
            dato[4]=rs.getString(5);
            
               
            model.addRow(dato);
            }
            TBperson.setModel(model);
        } catch (SQLException ex) {
            System.out.println(ex+"  es aca");
           
        }



}
    
      
       void mostrarFamilia(String valor){
    DefaultTableModel model = new DefaultTableModel();
    model.addColumn("Cedula");
    model.addColumn("Cedula personal");
    model.addColumn("Serial de Carne");
    model.addColumn("Nombre");
    model.addColumn("Apellido");
      
    model.addColumn("Parentezco");
    model.addColumn("Tlf");
    model.addColumn("Direccion");
    TBperson.setModel(model);
    String sql="";
    if(valor.equals("")){
    
    sql="SELECT * FROM familiares"; 
    
    }
    else{
    sql="SELECT * FROM familiares WHERE ced_per='"+valor+"'";
    
    }
        
    String []dato = new String[8];
        try {
            Statement st = cn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while(rs.next()){
            dato[0]=rs.getString(1);
            dato[1]=rs.getString(2);
            dato[2]=rs.getString(3); 
            dato[3]=rs.getString(4);
            dato[4]=rs.getString(5);
            dato[5]=rs.getString(6);
            dato[6]=rs.getString(7);
            dato[7]=rs.getString(8);    
            model.addRow(dato);
            }
            TBperson.setModel(model);
        } catch (SQLException ex) {
            System.out.println(ex+"  es aca");
           
        }
       
           
       
        /*
int[] anchos = {1, 20, 2, 20, 20,20, 20,20};

//hacemos un bucle FOR desde cero hasta la cantidad de columnas

//de nuestra tabla
for(int i = 0; i < TBperson.getColumnCount(); i++) {


TBperson.getColumnModel().getColumn(i).setPreferredWidth(anchos[i]);
}*/


}
    
       
    
    
    
    
    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:

     
        dispose();

    }//GEN-LAST:event_jLabel3MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Registros ir = new Registros();
        ir.setVisible(true);
        dispose();
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void BtnBuscarPERActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBuscarPERActionPerformed
        // TODO add your handling code here:
        
        
  mostrarD(TXTced.getText());
        
        
    }//GEN-LAST:event_BtnBuscarPERActionPerformed

    private void jButton58ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton58ActionPerformed
        // TODO add your handling code here:

        Parte ir= new Parte();
        ir.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton58ActionPerformed

    private void jButton57ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton57ActionPerformed
        // TODO add your handling code here:

        Formatos ir = new Formatos();
        ir.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton57ActionPerformed

    private void jButton56ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton56ActionPerformed
        // TODO add your handling code here:
        
        dispose();
    }//GEN-LAST:event_jButton56ActionPerformed

    private void jButton54ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton54ActionPerformed
        // TODO add your handling code here:
        Situacion ir = new Situacion();
        ir.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton54ActionPerformed

    private void jButton53ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton53ActionPerformed
        // TODO add your handling code here:

        Guardia11 ir = new Guardia11();
        ir.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton53ActionPerformed

    private void jButton52ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton52ActionPerformed
        // TODO add your handling code here:
/*
        Personal ir = new Personal();
        ir.setVisible(true);
//        dispose();*/ mostrarD("");
        BtnBuscarPER.setVisible(true);
  BtnBuscarArma.setVisible(false);
         BtnBuscarFame.setVisible(false);
         BtnBuscarProm.setVisible(false);
BTNbuscarSit.setVisible(false);
        
    }//GEN-LAST:event_jButton52ActionPerformed

    private void BotonPromActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonPromActionPerformed
        // TODO add your handling code here:
        String dato="";
        /*try{
        Statement s = cn.createStatement();
        ResultSet rs = s.executeQuery("SELECT * FROM personal WHERE ced_per='"+TXTced.getText()+"'");
    
         while (rs.next()){
        dato=rs.getString("id_prom");
            System.out.println(dato);}}
         catch(Exception e){}*/
        mostrarPromo(dato);
        
        BtnBuscarPER.setVisible(false);
  BtnBuscarArma.setVisible(false);
         BtnBuscarFame.setVisible(false);
         BtnBuscarProm.setVisible(true);

        BTNbuscarSit.setVisible(false);
        
        
    }//GEN-LAST:event_BotonPromActionPerformed

    private void BotonArmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonArmaActionPerformed
        // TODO add your handling code here:
        
        String dato="";
        /*try{
        Statement s = cn.createStatement();
        ResultSet rs = s.executeQuery("SELECT * FROM personal WHERE ced_per='"+TXTced.getText()+"'");
    
         while (rs.next()){
        dato=rs.getString("ser_armp");
            System.out.println(dato);}}
         catch(Exception e){}*/
        mostrararma(dato);
 
        BtnBuscarPER.setVisible(false);
  BtnBuscarArma.setVisible(true);
         BtnBuscarFame.setVisible(false);
         BtnBuscarProm.setVisible(false);

        BTNbuscarSit.setVisible(false);
        

        
    }//GEN-LAST:event_BotonArmaActionPerformed

    private void BotonFamiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonFamiActionPerformed
        // TODO add your handling code here:
        
                mostrarFamilia("");
                BtnBuscarPER.setVisible(false);
  BtnBuscarArma.setVisible(false);
         BtnBuscarFame.setVisible(true);
         BtnBuscarProm.setVisible(false);

                BTNbuscarSit.setVisible(false);
                
        
        
    }//GEN-LAST:event_BotonFamiActionPerformed

    private void CMBBUSCARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CMBBUSCARActionPerformed
        // TODO add your handling code here:

        String dato=(String)CMBBUSCAR.getSelectedItem();
        
        mostrarUni(dato);
        
        
        
        
    }//GEN-LAST:event_CMBBUSCARActionPerformed

    private void jButton59ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton59ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton59ActionPerformed

    private void BtnBuscarPromActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBuscarPromActionPerformed
        // TODO add your handling code here:
        
        String dato="";
        try{
        Statement s = cn.createStatement();
        ResultSet rs = s.executeQuery("SELECT * FROM personal WHERE ced_per='"+TXTced.getText()+"'");
    
         while (rs.next()){
        dato=rs.getString("id_prom");
            System.out.println(dato);}}
         catch(Exception e){}
        mostrarPromo(dato);
        
        
        
    }//GEN-LAST:event_BtnBuscarPromActionPerformed

    private void BtnBuscarFameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBuscarFameActionPerformed
        // TODO add your handling code here:
        
        
        
        mostrarFamilia(TXTced.getText());
        
        
    }//GEN-LAST:event_BtnBuscarFameActionPerformed

    private void BtnBuscarArmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBuscarArmaActionPerformed
        // TODO add your handling code here:
        
        String dato="";
        try{
        Statement s = cn.createStatement();
        ResultSet rs = s.executeQuery("SELECT * FROM personal WHERE ced_per='"+TXTced.getText()+"'");
    
         while (rs.next()){
        dato=rs.getString("ser_armp");
            System.out.println(dato);}}
         catch(Exception e){}
        mostrararma(dato);
        
        
    }//GEN-LAST:event_BtnBuscarArmaActionPerformed

    private void BotonArma1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonArma1ActionPerformed
        // TODO add your handling code here:
        mostrarSitua("");
        
        BtnBuscarPER.setVisible(false);
  BtnBuscarArma.setVisible(false);
         BtnBuscarFame.setVisible(false);
         BtnBuscarProm.setVisible(false);
         BTNbuscarSit.setVisible(true);
        
        
    }//GEN-LAST:event_BotonArma1ActionPerformed

    private void BTNbuscarSitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNbuscarSitActionPerformed
        // TODO add your handling code here:
        
        mostrarSitua(TXTced.getText());
        
    }//GEN-LAST:event_BTNbuscarSitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }}
             } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Personal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Personal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Personal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Personal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Personal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNbuscarSit;
    private javax.swing.JButton BotonArma;
    private javax.swing.JButton BotonArma1;
    private javax.swing.JButton BotonFami;
    private javax.swing.JButton BotonProm;
    private javax.swing.JButton BtnBuscarArma;
    private javax.swing.JButton BtnBuscarFame;
    private javax.swing.JButton BtnBuscarPER;
    private javax.swing.JButton BtnBuscarProm;
    private javax.swing.JLabel CEA;
    private javax.swing.JComboBox CMBBUSCAR;
    private javax.swing.JLabel Centr;
    private javax.swing.JLabel JLnombreUSU;
    private javax.swing.JTable TBperson;
    private javax.swing.JTextField TXTced;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton52;
    private javax.swing.JButton jButton53;
    private javax.swing.JButton jButton54;
    private javax.swing.JButton jButton56;
    private javax.swing.JButton jButton57;
    private javax.swing.JButton jButton58;
    private javax.swing.JButton jButton59;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables


Conectar cc=new Conectar();
Connection cn = cc.conexion();


}
